version: '3.8'

services:
  airbnb-scraper:
    build: .
    container_name: airbnb_availability_scraper
    restart: unless-stopped
    volumes:
      - ./disponibilidade_airbnb.csv:/app/disponibilidade_airbnb.csv
