version: '3.8'

services:
  airbnb-scraper:
    image: ghcr.io/juniorsereno/playwright:latest # O Easypanel irá construir a imagem a partir do seu repositório
    container_name: airbnb_availability_scraper
    restart: unless-stopped
    volumes:
      - ./disponibilidade_airbnb.csv:/app/disponibilidade_airbnb.csv
