services:
  airbnb-scraper:
    build: .
    restart: unless-stopped
    # A seção de volumes foi removida, pois os dados agora são enviados via webhook.
    # Se precisar depurar e salvar screenshots, você pode descomentar a linha abaixo.
    # volumes:
    #   - ./data:/app/data
